version: '3.2'
services:
  mysql:
    image: mysql:5.6.22
    container_name: mysql_cont
    volumes:
      - ~/work/mysql-data:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      MYSQL_USER: 'root'
      MYSQL_ROOT_HOST: '%'